/* Generated By:JavaCC: Do not edit this line. DTOELParserConstants.java */
package com.googlecode.bumblebee.dto.el.parser;

public interface DTOELParserConstants {

    int EOF = 0;
    int THIS = 6;
    int DOT = 7;
    int NULL = 8;
    int LONG = 9;
    int INTEGER = 10;
    int DECIMAL = 11;
    int IDENTIFIER = 12;
    int STRING = 13;
    int PARAMETER = 14;

    int DEFAULT = 0;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"this\"",
            "\".\"",
            "\"null\"",
            "<LONG>",
            "<INTEGER>",
            "<DECIMAL>",
            "<IDENTIFIER>",
            "<STRING>",
            "<PARAMETER>",
    };

}
